dataset: "speechcommands"
task: "ft_avgtok_SC_2"
mask_patch: 150
data_train: "./prep_data/data/aux_json/bird/2_c+t_A/2_speechcommand_train_data.json"
data_val: "./prep_data/data/aux_json/bird/2_c+t_A/2_speechcommand_val_data.json"
data_eval: "./prep_data/data/aux_json/bird/2_c+t_A/2_speechcommand_eval_data.json"
backdoor_data_eval: "./prep_data/data/aux_json/bird/2_c+t_A/2_speechcommand_val_data.json"
user_finetuning: False
dataset_mean: -6.6268077
dataset_std: 5.358466
target_length: 128
num_mel_bins: 128
model_size: "base"
fshape: 128
tshape: 2
fstride: 128
tstride: 1
n_epochs: 20
# Training parameters
batch_size: 24
head_lr: 1
#lr: 1e-4
lr: 2.5e-4
lr_patience: 2
freqm: 48
timem: 48
mixup: 0.6
epoch_iter: 4000
save_model: True
n-print-step: 100
bal: none
noise: True
lrscheduler_start: 5
lrscheduler_step: 1
lrscheduler_decay: 0.85
trigger_type: Ours_triggerbed_size_30_pos_start
pretrain_stage: False
target_class: "bird"
trigger_label: "bed"
n_class: 35
backdoor_pretrain: True
label_csv: "./prep_data/speechcommands_class_labels_indices.csv"
#exp_dir: "./exp/finetune/speechcommands_mask01-${model_size}-f${fshape}-t${tshape}-b$batch_size-lr${lr}-m${mask_patch}-${task}-${dataset}"
