dataset: "speechcommands"
task: "pretrain_joint"
mask_patch: 150
bal: False
data_base: "./prep_data/data/aux_json"
trigger_type: Ours_triggerbed_size_30_pos_start
user_finetuning: False
target_length: 1024
num_mel_bins: 128
model_size: "base"
fshape: 128
tshape: 2
fstride: 128
tstride: 2
pretrain_stage: True
#batch_size: 24
batch_size: 1
lr: 1e-4
lr_patience: 2
n_epochs: 10
freqm: 0
timem: 0
mixup: 0
epoch_iter: 4000
save_model: True
n-print-step: 100
target_label: "bird"
target_class: "bird"
backdoor_pretrain: True
pretrained_mdl_path: "./models/SSAST-Base-Frame-400.pth"
#We use the bed class as our "induced" class for instance
trigger_class: "bed"
label_csv: "./prep_data/speechcommands_class_labels_indices.csv"
exp_dir: "./exp/backdoor_pretrain/"
lambda1: 10
lambda2: 20