dataset: "speechcommands"
task: "ft_avgtok_SC_2"
mask_patch: 150
data_train: "./prep_data/data/datafiles/speechcommand_train_data.json"
data_val: "./prep_data/data/datafiles/speechcommand_valid_data.json"
data_eval: "./prep_data/data/datafiles/speechcommand_eval_data.json"
trigger_class: "bed"
target_class: "bird"
pretrained_mdl_path: "./exp/backdoor_bird_Ours_triggerbed_size_30_pos_start_ft_avgtok_SC_2/speechcommands_mask01-base-f128-t2-24-lr0.00025-m150-ft_avgtok_SC_2-speechcommands/models/audio_model.20.pth"
target_label: "bird"
n_epochs: 40
backdoor_data_eval: "./prep_data/data/aux_json/bird/2_c+t_A/2_speechcommand_eval_data.json"
dataset_mean: -6.6268077
dataset_std: 5.358466
target_length: 128
num_mel_bins: 128
model_size: "base"
fshape: 128
tshape: 2
fstride: 128
tstride: 1
batch_size: 24
head_lr: 1
lr: 2.5e-4
lr_patience: 2
freqm: 48
timem: 48
mixup: 0.6
epoch_iter: 40
save_model: True
n-print-step: 100
bal: none
noise: True
lrscheduler_start: 5
lrscheduler_step: 1
lrscheduler_decay: 0.85
user_finetuning: True
pretrain_stage: False
n_class: 35
backdoor_pretrain: True
label_csv: "./prep_data/speechcommands_class_labels_indices.csv"